
import streamlit as st
import pandas as pd
import joblib
import numpy as np
import plotly.express as px

st.set_page_config(page_title="Battery RUL Predictor", layout="wide")
st.title("🔋 Battery Remaining Useful Life (RUL) Predictor")

st.markdown("This application predicts the Remaining Useful Life (RUL) of batteries using a pre-trained machine learning model. Adjust the input parameters in the sidebar or upload your own dataset to see predictions.   ")

# Load model and data
@st.cache_resource
def load_model(path='model/rul_model_rf.joblib'):
    return joblib.load(path)

@st.cache_data
def load_data(path='data/battery_data.csv'):
    return pd.read_csv(path)

model = load_model()
data = load_data()

with st.sidebar:
    st.header('🔧 Input Controls')
    voltage = st.slider('Voltage (V)', 2.5, 4.5, 3.8, step=0.01)
    current = st.slider('Current (A)', 0.05, 2.0, 0.5, step=0.01)
    temperature = st.slider('Temperature (°C)', 0.0, 80.0, 30.0, step=0.1)
    cycle = st.number_input('Cycle Number', min_value=1, max_value=10000, value=100)
    show_curve = st.checkbox('Show degradation curve (predicted RUL vs cycle)', value=True)

    uploaded = st.file_uploader('Upload CSV (optional)', type=['csv'])

st.subheader('📊 Dataset preview')
st.dataframe(data.head(10))

# If user uploaded CSV, use it for predictions
if uploaded is not None:
    user_df = pd.read_csv(uploaded)
    st.write('Uploaded data preview:')
    st.dataframe(user_df.head())
    features = user_df[['voltage','current','temperature','cycle']]
    preds = model.predict(features)
    user_df['predicted_RUL'] = preds
    st.subheader('Predictions for uploaded data')
    st.dataframe(user_df.head(20))
    fig2 = px.line(user_df, x='cycle', y='predicted_RUL', title='Predicted RUL over cycles (uploaded)')
    st.plotly_chart(fig2, use_container_width=True)
else:
    # Single prediction
    input_df = pd.DataFrame([{
        'voltage': voltage, 'current': current, 'temperature': temperature, 'cycle': cycle
    }])
    pred = model.predict(input_df)[0]
    st.success(f'🔮 Predicted Remaining Useful Life: **{pred:.2f} cycles**')

# Degradation curve using dataset + model
if show_curve:
    st.subheader('📈 Predicted RUL over dataset cycles')
    df = data.copy()
    features = df[['voltage','current','temperature','cycle']]
    df['predicted_RUL'] = model.predict(features)
    fig = px.line(df, x='cycle', y=['RUL','predicted_RUL'], labels={'value':'RUL (cycles)'}, title='Actual RUL vs Predicted RUL over cycles')
    st.plotly_chart(fig, use_container_width=True)

st.markdown('---')
st.caption('Project generated by ChatGPT — Battery RUL Predictor')
